### ISSUE TITLE
about your paper

### ISSUE THREAD

**Issue by konioyxgq** [ShawnXYang/Face-Robustness-Benchmark#1]
Thank you very much for sharing. When reading your paper, I saw Figure 1. I tried to get attention maps, but it failed. Can you share this part of the visual work? thank you very much

**Comment by ShawnXYang** [comment]
Hi, we mainly refer to this code [https://github.com/yizt/Grad-CAM.pytorch] to obtain attention maps. Hope this helps you.

**Comment by konioyxgq** [comment]
Thank you very much for your reply. This helped me.
